Add controler in product and brand
anacsv/catalog pull request #31
Opened 2020-08-11 20:29 UTC by anacsv

2020-08-11 20:39 UTC, matheusreis0 requested changes

2020-08-11 20:39 UTC, matheusreis0 commented on app/controller/product_controller.py
> +        return jsonify([p.__dict__() for p in self.__dao.read(id)])
Nao precisa passar o id nesse read, nao passando ele passa pro read all no base dao

2020-08-11 20:49 UTC, anacsv reviewed
Ok

2020-08-11 20:51 UTC, matheusreis0 approved these changes

2020-08-12 12:43 UTC, pauloestrella1994 commented on app/controller/product_controller.py
> +            return jsonify(self.__dao.read().__dict__())
Nessa linha deve permanecer o id, visto que o condicional "if" pressupõe a passagem de um id para o read (get_by_id)

2020-08-12 12:52 UTC, pauloestrella1994 approved these changes

2020-08-12 12:59 UTC, merged